In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

In [3]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [5]:
arr = np.array(my_list)   # converting list to array
arr

array([0, 1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [8]:
np.arange(10)  #arange it will print the value within interval 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(10,15) 

array([10, 11, 12, 13, 14])

In [9]:
np.arange(10,20,5)

array([10, 15])

In [13]:
np.arange(10,20,5,2)

TypeError: Cannot interpret '2' as a data type

In [10]:
np.zeros(5) #parameter tunning 

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(5, dtype=int) #hyperparameter tunning 

array([0, 0, 0, 0, 0])

In [16]:
np.zeros([2,2], dtype = int) #2d array

array([[0, 0],
       [0, 0]])

In [17]:
np.zeros([5,10], dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones([3,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
np.ones([3,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [16]:
np.arange(20, 10)

array([], dtype=int64)

In [17]:
np.arange(-20, 10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [18]:
np.twos(3)

AttributeError: module 'numpy' has no attribute 'twos'

In [29]:
np.threes(3)

AttributeError: module 'numpy' has no attribute 'threes'

In [19]:
random.rand(3,2)

NameError: name 'random' is not defined

In [21]:
np.random.rand(2)

array([0.12612996, 0.31317959])

In [22]:
np.random.rand(5)

array([0.34640935, 0.71572261, 0.37985668, 0.08954054, 0.03836129])

In [23]:
np.random.rand(3,2)

array([[0.55524513, 0.88119264],
       [0.84528654, 0.53136557],
       [0.88056207, 0.32686293]])

In [26]:
np.random.randint(3)

0

In [29]:
np.random.randint(5,10)

8

In [72]:
np.random.randint(5,10,3)

array([9, 7, 7], dtype=int32)

In [73]:
ran = np.random.randint(5,10,3)
print(ran)

[8 9 6]


In [30]:
otp = np.random.randint(5,10,4)
print(otp)

[8 8 6 9]


In [31]:
arr0 = np.random.randint(10,40,(10,10))
print(arr0)

[[17 28 16 35 37 10 14 33 39 15]
 [13 34 14 24 36 32 37 17 35 13]
 [27 11 22 10 12 25 29 37 27 29]
 [16 13 34 20 35 28 22 20 37 29]
 [31 22 10 32 11 19 35 17 26 16]
 [32 14 13 36 12 27 18 20 32 39]
 [16 16 29 11 27 19 26 27 37 10]
 [13 30 36 17 16 38 19 36 25 34]
 [39 33 11 30 35 11 24 16 20 10]
 [34 27 37 11 13 23 28 23 24 23]]


In [32]:
arr0

array([[17, 28, 16, 35, 37, 10, 14, 33, 39, 15],
       [13, 34, 14, 24, 36, 32, 37, 17, 35, 13],
       [27, 11, 22, 10, 12, 25, 29, 37, 27, 29],
       [16, 13, 34, 20, 35, 28, 22, 20, 37, 29],
       [31, 22, 10, 32, 11, 19, 35, 17, 26, 16],
       [32, 14, 13, 36, 12, 27, 18, 20, 32, 39],
       [16, 16, 29, 11, 27, 19, 26, 27, 37, 10],
       [13, 30, 36, 17, 16, 38, 19, 36, 25, 34],
       [39, 33, 11, 30, 35, 11, 24, 16, 20, 10],
       [34, 27, 37, 11, 13, 23, 28, 23, 24, 23]], dtype=int32)

In [39]:
arr1 = np.random.randint(1,5,(4,3))
print(arr1)

[[2 3 2]
 [2 4 3]
 [4 3 4]
 [1 3 1]]


# , indexing, slicing in array

In [40]:
arr1[:]

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [42]:
len(arr1) # 

4

In [44]:
arr1.shape

(4, 3)

In [45]:
arr0.shape

(10, 10)

In [46]:
len(arr0)

10

In [47]:
arr1

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [50]:
arr1[-2] # print row 

array([4, 3, 4], dtype=int32)

In [51]:
arr1[1]  # print row 

array([2, 4, 3], dtype=int32)

In [52]:
arr1

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [55]:
arr1[:,-1] 

array([2, 3, 4, 1], dtype=int32)

In [56]:
arr1[:,2] 

array([2, 3, 4, 1], dtype=int32)

In [57]:
arr1

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [58]:
arr1[0]

array([2, 3, 2], dtype=int32)

In [59]:
v = arr1[1, 2]
print(v)

3


In [62]:
arr0

array([[17, 28, 16, 35, 37, 10, 14, 33, 39, 15],
       [13, 34, 14, 24, 36, 32, 37, 17, 35, 13],
       [27, 11, 22, 10, 12, 25, 29, 37, 27, 29],
       [16, 13, 34, 20, 35, 28, 22, 20, 37, 29],
       [31, 22, 10, 32, 11, 19, 35, 17, 26, 16],
       [32, 14, 13, 36, 12, 27, 18, 20, 32, 39],
       [16, 16, 29, 11, 27, 19, 26, 27, 37, 10],
       [13, 30, 36, 17, 16, 38, 19, 36, 25, 34],
       [39, 33, 11, 30, 35, 11, 24, 16, 20, 10],
       [34, 27, 37, 11, 13, 23, 28, 23, 24, 23]], dtype=int32)

In [63]:
arr0[-7]

array([16, 13, 34, 20, 35, 28, 22, 20, 37, 29], dtype=int32)

In [64]:
arr0[:, -7]

array([35, 24, 10, 20, 32, 36, 11, 17, 30, 11], dtype=int32)

In [65]:
arr0

array([[17, 28, 16, 35, 37, 10, 14, 33, 39, 15],
       [13, 34, 14, 24, 36, 32, 37, 17, 35, 13],
       [27, 11, 22, 10, 12, 25, 29, 37, 27, 29],
       [16, 13, 34, 20, 35, 28, 22, 20, 37, 29],
       [31, 22, 10, 32, 11, 19, 35, 17, 26, 16],
       [32, 14, 13, 36, 12, 27, 18, 20, 32, 39],
       [16, 16, 29, 11, 27, 19, 26, 27, 37, 10],
       [13, 30, 36, 17, 16, 38, 19, 36, 25, 34],
       [39, 33, 11, 30, 35, 11, 24, 16, 20, 10],
       [34, 27, 37, 11, 13, 23, 28, 23, 24, 23]], dtype=int32)

In [66]:
arr0[3:4, 2:6]

array([[34, 20, 35, 28]], dtype=int32)

In [67]:
arr1

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [68]:
arr1[1] 

array([2, 4, 3], dtype=int32)

In [69]:
arr1[1,2] # 1 first row & 2 means colums 

np.int32(3)

In [70]:
arr1

array([[2, 3, 2],
       [2, 4, 3],
       [4, 3, 4],
       [1, 3, 1]], dtype=int32)

In [71]:
arr1[1:2]

array([[2, 4, 3]], dtype=int32)