In [1]:
import numpy as np 

In [2]:
np.__version__

'1.26.4'

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [8]:
type(my_list)

list

In [9]:
arr = np.array(my_list) 
arr

array([0, 1, 2, 3, 4, 5])

In [11]:
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(10, 20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [15]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5, dtype=int) 

array([0, 0, 0, 0, 0])

In [18]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.zeros((10, 5) ,dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [22]:
np.ones(4)

array([1., 1., 1., 1.])

In [23]:
np.ones((4,5)) 

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
np.ones((4,5), dtype = int) 

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [25]:
np.twos(4)

AttributeError: module 'numpy' has no attribute 'twos'

In [26]:
random(2)

NameError: name 'random' is not defined

In [27]:
random.rand(2)

NameError: name 'random' is not defined

In [28]:
rand(3,2) 

NameError: name 'rand' is not defined

In [34]:
np.random.rand(4)

array([0.52060276, 0.83740628, 0.07427959, 0.56682285])

In [35]:
np.random.rand(10)

array([0.58163611, 0.91859361, 0.65090598, 0.78759313, 0.03411245,
       0.63612359, 0.68206706, 0.86085161, 0.42650259, 0.19641268])

In [36]:
np.random.rand(3,2) 

array([[0.19966015, 0.94360741],
       [0.67660448, 0.33116055],
       [0.55912645, 0.98375915]])

In [46]:
np.random.randint(5) 

3

In [51]:
np.random.randint(5, 10) 

5

In [68]:
np.random.randint(5, 10, 4)

array([6, 9, 6, 6])

In [67]:
np.random.randint(5, 10, [5,7])

array([[6, 6, 7, 7, 7, 6, 9],
       [7, 6, 6, 7, 8, 8, 5],
       [5, 5, 8, 5, 7, 6, 6],
       [5, 5, 6, 9, 5, 6, 6],
       [8, 5, 7, 8, 6, 8, 6]])

In [69]:
np.random.randint(10, 2) 

ValueError: low >= high

In [76]:
np.random.randint(-10, 2) 

-5

In [80]:
np.random.randint(-10, 2, 5) 

array([-4,  0, -4, -6,  1])

In [81]:
np.random.randint(10,40,(10,10)) 

array([[14, 29, 13, 20, 12, 20, 28, 23, 33, 31],
       [17, 11, 16, 39, 12, 16, 35, 31, 15, 33],
       [35, 36, 12, 20, 35, 33, 32, 22, 19, 13],
       [20, 10, 25, 14, 22, 39, 16, 37, 25, 36],
       [31, 31, 32, 24, 24, 29, 18, 23, 10, 31],
       [34, 21, 28, 11, 38, 20, 29, 23, 16, 10],
       [32, 36, 33, 17, 25, 38, 10, 13, 31, 13],
       [38, 21, 37, 22, 37, 15, 18, 37, 30, 28],
       [33, 15, 39, 32, 33, 18, 33, 21, 17, 24],
       [35, 33, 19, 23, 26, 27, 18, 32, 27, 13]])

In [82]:
arr1 = np.random.randint(10,40,(10,10))

In [83]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [84]:
print(arr1)

[[14 36 29 33 18 34 26 28 22 21]
 [33 29 21 33 34 33 11 19 31 13]
 [30 25 38 28 31 38 19 32 22 17]
 [10 17 18 39 28 26 11 18 10 14]
 [33 11 38 32 39 38 12 38 37 37]
 [33 27 36 26 33 26 32 14 10 18]
 [39 19 29 19 25 11 16 33 14 11]
 [34 28 10 22 21 34 14 32 23 38]
 [11 39 23 35 10 22 24 21 35 16]
 [37 22 28 37 28 27 38 20 31 11]]


# indexing & slicing in array

In [86]:
arr1[:] 

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [87]:
len(arr1)

10

In [89]:
arr1.shape  # DIMENSION OF AN ARRAY ( ROW & COLUMN COUNT)

(10, 10)

In [90]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [91]:
arr1[3] 

array([10, 17, 18, 39, 28, 26, 11, 18, 10, 14])

In [92]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [93]:
arr1[2:7]

array([[30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11]])

In [94]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [95]:
arr1[2, 7] 

32

In [96]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [97]:
arr2 = np.random.randint(1,10,(3,3))
arr2

array([[8, 2, 2],
       [2, 9, 8],
       [4, 6, 2]])

In [98]:
arr2[::-1] 

array([[4, 6, 2],
       [2, 9, 8],
       [8, 2, 2]])

In [99]:
arr1

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37],
       [33, 27, 36, 26, 33, 26, 32, 14, 10, 18],
       [39, 19, 29, 19, 25, 11, 16, 33, 14, 11],
       [34, 28, 10, 22, 21, 34, 14, 32, 23, 38],
       [11, 39, 23, 35, 10, 22, 24, 21, 35, 16],
       [37, 22, 28, 37, 28, 27, 38, 20, 31, 11]])

In [100]:
arr1[:5] 

array([[14, 36, 29, 33, 18, 34, 26, 28, 22, 21],
       [33, 29, 21, 33, 34, 33, 11, 19, 31, 13],
       [30, 25, 38, 28, 31, 38, 19, 32, 22, 17],
       [10, 17, 18, 39, 28, 26, 11, 18, 10, 14],
       [33, 11, 38, 32, 39, 38, 12, 38, 37, 37]])