In [ ]:
# Numpy Crash Course

In [83]:
import numpy as np

In [84]:
np.__version__

'1.26.3'

In [85]:
import sys 
sys.version

'3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]'

## Creating LIST

In [86]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [87]:
type(my_list)

list

# below code we are converting list to array

In [ ]:
#!pip install numpy

In [88]:
arr = np.array(my_list) 

In [89]:
arr

array([0, 1, 2, 3, 4, 5])

In [90]:
type(arr)

numpy.ndarray

In [91]:
type(my_list)

list

In [92]:
np. # we learn important function 

SyntaxError: invalid syntax (1655120754.py, line 1)

In [ ]:
np.arange(10) 

In [ ]:
np.arange(5.0)  

In [ ]:
np.arange(9) 

In [ ]:
np.arange(0, 5)

In [ ]:
np.arange(10,20) 

In [ ]:
np.arange(20,10) # 1st arg < 2nd arg

In [ ]:
np.arange(-20,10) 

In [ ]:
np.arange(-16,10) 

In [ ]:
np.arange(-20,-10) 

In [ ]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

In [ ]:
ar = np.arange(-30,20)
ar

In [ ]:
np.arange(10,10) 

In [ ]:
np.arange()

In [ ]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

In [ ]:
np.arange(0,10,3)

In [ ]:
np.arange(10,30,5,8)

In [ ]:
np.zeros(10) # parameter  tunning 

In [ ]:
np.zeros(5, dtype=int) # hyperparameter tunning 

In [ ]:
np.zeros((2,2), dtype=int)

In [ ]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

In [ ]:
zero = np.zeros([2,2])
print(zero)

print('####')

print(type(zero))

In [ ]:
np.zeros((2,10))

In [ ]:
np.zeros((2,2))

In [ ]:
np.zeros((3,3))

In [ ]:
np.zeros((10,30))

In [ ]:
np.zeros((10,10),dtype = int)

In [ ]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

In [ ]:
n = (6,7)
n1 = (6,8)
print(np.zeros(n1)) # parameter tunnin g

In [ ]:
print(np.zeros(n,dtype=int)) ## hypyerparameter tunning 

In [ ]:
n

In [ ]:
n1

In [ ]:
print(np.zeros(n1))

In [ ]:
np.ones(3)

In [ ]:
np.ones((3,3))

In [ ]:
np.ones(4, dtype=int) 

In [ ]:
np.ones(4)

In [ ]:
n

In [ ]:
np.ones(n)

In [ ]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

In [ ]:
np.t

In [ ]:
np.two((2,3)) 

In [ ]:
np.three(2,3) 

In [ ]:
np.ones(2)

In [ ]:
np.ones((2,4)) 

In [ ]:
np.ones((6,10),dtype = int) 

In [ ]:
np.twos((2,4))

In [ ]:
np.

In [ ]:
np.three((2,4))

In [ ]:
range(5)

In [ ]:
r = range(5)
r

In [ ]:
for i in r:
    print(i)

In [ ]:
list(range(5))

In [ ]:
range(1,10)

In [ ]:
list(range(1,10))

In [ ]:
list(range(1,10,3))

In [ ]:
y = list(range(12))
y

In [ ]:
rand(3,2)

In [ ]:
random.rand(3,2)

In [ ]:
np.random.rand(5)

In [ ]:
np.rand(4)

In [ ]:
np.random.rand(3,5)

In [ ]:
np.random.randint(4,6)

In [ ]:
np.random.randint(2,20,4) # 2nd argument is exlusive 

In [ ]:
np.random.randint(0,1) 

In [ ]:
np.random.randint(10,20,5)

In [ ]:
np.random.randint(1,6,4)

In [ ]:
np.random.rand(3)

In [ ]:
np.random.randint(1)  

In [ ]:
np.random.randint(30,20,10) 

In [ ]:
np.random.randint(-30,20,10) 

In [ ]:
np.random.randint(20,30,10) 

In [ ]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

In [ ]:
np.random.randint(10,21,3)

In [ ]:
np.random.randint(1,12,10)

In [ ]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
np.random.randint(1,100,(12,12)) #generre the element 10 -30 with 4*4 mtri

In [ ]:
np.arange(1,13)

In [ ]:
np.arange(1,13).reshape(3,4)

In [ ]:
np.arange(1,13).reshape(4,3)

In [ ]:
np.arange(1,13).reshape(5,4)

In [ ]:
np.arange(1,13).reshape(6,2)

In [ ]:
np.arange(1,13).reshape(12,1)

# slicing in matrix

In [81]:
b = np.random.randint(10,20,(5,4))
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [82]:
type(b)

numpy.ndarray

In [93]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [94]:
b[:] 

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [95]:
b[1:3]

array([[11, 14, 17, 16],
       [17, 18, 10, 15]])

In [96]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [97]:
b[1,2]

17

In [98]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [99]:
b[1,3]

16

In [100]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [101]:
b[1,-1]

16

In [102]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [103]:
b[2:3]

array([[17, 18, 10, 15]])

In [104]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [105]:
b[0:-2] 

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15]])

In [106]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [107]:
b[0,2] 

13

In [108]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [110]:
b[-5,3] 

16

In [111]:
b[-5,-3]

19

In [112]:
b

array([[11, 19, 13, 16],
       [11, 14, 17, 16],
       [17, 18, 10, 15],
       [11, 19, 19, 14],
       [11, 15, 17, 12]])

In [113]:
b[-4,2] 

17

In [ ]:
np.random.randint(10,20,(4,4))

In [ ]:
b 

In [ ]:
b[-4,-2]

In [ ]:
b

In [ ]:
b[-4:2] 

In [ ]:
b[:]

## Operations

In [117]:
a = np.random.randint(10,20,10)
a

array([15, 17, 18, 17, 19, 11, 17, 15, 14, 12])

In [119]:
id(a)

2325687534096

In [120]:
arr

array([0, 1, 2, 3, 4, 5])

In [123]:
arr2 = np.random.randint(0,100,(10,10))

In [122]:
arr2

array([[41, 90, 74, 43, 86, 68, 16, 58, 33, 95],
       [72, 67, 96, 65, 63, 78, 29, 18, 98, 43],
       [18,  9, 20, 84, 14, 97,  0, 14, 27, 63],
       [52, 74, 45, 54, 28, 97,  9, 85, 48, 36],
       [48, 18, 20,  8, 69, 58, 15, 58, 91,  2],
       [ 9, 72, 15, 27, 11, 78, 51, 99,  9, 35],
       [ 7, 78, 85, 66, 47,  3, 94, 44, 77, 65],
       [98, 78,  1, 92, 78, 82, 65, 12, 15, 69],
       [99, 92, 80, 17,  1, 69, 90, 64,  7, 13],
       [47, 49, 57, 17, 68, 82, 92, 90, 47, 16]])

In [ ]:
arr

In [124]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [125]:
arr

array([0, 1, 2, 3, 4, 5])

In [126]:
arr[:4] 

array([0, 1, 2, 3])

In [127]:
arr2[:]

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [128]:
arr2[0:5] 

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52]])

In [129]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [130]:
arr2[1,4] 

78

In [ ]:
arr2

In [ ]:
arr2[-5,5] 

In [ ]:
arr2[-5,-5] 

In [ ]:
arr2

In [ ]:
arr2[-5,-5]

In [ ]:
arr2

In [ ]:
arr2[-1,-2]

In [131]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [132]:
arr2[::-1]

array([[35,  7, 39, 67, 74,  3, 74, 62, 41, 11],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [12, 69, 81,  4, 62, 76, 44, 86, 63, 62]])

In [133]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [134]:
arr2[::-2] 

array([[35,  7, 39, 67, 74,  3, 74, 62, 41, 11],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83]])

In [135]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [136]:
arr2[::-3]

array([[35,  7, 39, 67, 74,  3, 74, 62, 41, 11],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [12, 69, 81,  4, 62, 76, 44, 86, 63, 62]])

In [137]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [138]:
arr2[:-3] 

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47]])

In [139]:
arr2

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [34, 34, 16, 31, 78, 98, 92, 66, 82, 83],
       [44, 66, 70, 62, 73, 56, 31, 56, 23, 67],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [92, 35, 80, 42,  4, 21, 74, 75, 19, 52],
       [31, 19, 90, 83, 15, 70, 91, 61,  2,  9],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [69, 71, 79, 18, 28, 55, 75, 67, 26, 13],
       [67, 38, 53, 88, 21, 94, 35, 46, 70, 92],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [150]:
arr2[0:10:3]

array([[12, 69, 81,  4, 62, 76, 44, 86, 63, 62],
       [20, 81, 10, 90, 18, 91, 39, 67, 33, 22],
       [78, 95, 34, 86, 85, 40,  9,  1, 35, 47],
       [35,  7, 39, 67, 74,  3, 74, 62, 41, 11]])

In [ ]:
arr2

In [ ]:
arr2[3:]

In [151]:
arr

array([0, 1, 2, 3, 4, 5])

In [152]:
arr.max() 

5

In [153]:
arr.min()

0

In [154]:
arr

array([0, 1, 2, 3, 4, 5])

In [155]:
arr.mean()

2.5

In [156]:
arr

array([0, 1, 2, 3, 4, 5])

In [157]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [158]:
from numpy import * # 256 function called internally
a = array([1,2,3,4,9])
median(a)

3.0

# Without work on import* can you please find the median, mode)

In [159]:
arr

array([0, 1, 2, 3, 4, 5])

In [160]:
arr.reshape(3,2)  

array([[0, 1],
       [2, 3],
       [4, 5]])

In [161]:
arr.reshape(6,1)  

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [162]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [163]:
arr

array([0, 1, 2, 3, 4, 5])

In [164]:
arr.reshape(2,4) 

ValueError: cannot reshape array of size 6 into shape (2,4)

In [165]:
arr

array([0, 1, 2, 3, 4, 5])

In [166]:
arr.reshape(3,2,order='C') 

array([[0, 1],
       [2, 3],
       [4, 5]])

In [167]:
arr.reshape(2,3,order='C') 

array([[0, 1, 2],
       [3, 4, 5]])

In [168]:
arr.reshape(2,3,order='F') # print element with fortran 

array([[0, 2, 4],
       [1, 3, 5]])

In [169]:
arr.reshape(2,3,order='A') # A almost give you c type output 

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="C"):
	print(num_array,end=' ')

In [ ]:
# importing Numpy package 
import numpy as np

# creating a Numpy array
num_array = np.arange(100).reshape(20, 5)
print(num_array)

# Display array in Fortran order 

print("\n  C type array:")
for num_array in np.nditer(num_array, order="F"):
	print(num_array,end=' ')

In [ ]:
arr.

In [ ]:
arr.reshape(2,3)

In [ ]:
arr.reshape(1,4)  

In [ ]:
arr.reshape(1,6)  

In [ ]:
arr.reshape(6,1)  

In [ ]:
arr.reshape(2,6) 

In [ ]:
arr.reshape(3,3) 

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

## Indexing

In [170]:
mat = np.arange(0,100).reshape(10,10) 

In [171]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [172]:
row = 4
col = 5

In [173]:
col

5

In [174]:
row

4

In [175]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [176]:
mat[row,col] 

45

In [ ]:
mat[4,5] 

In [ ]:
mat

In [ ]:
mat[:]

In [177]:
col = 6

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[7] # befault it represent to rows

array([60, 61, 62, 63, 64, 65, 66, 67, 68, 69])

In [180]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [181]:
# With Slices
mat[:,col] 

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [182]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [184]:
mat[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [ ]:
mat

In [ ]:
mat[row,:] 

In [ ]:
mat

In [ ]:
mat[:,8]

In [ ]:
mat

In [ ]:
mat[:col] 

In [ ]:
mat[:6]

In [ ]:
row

In [ ]:
mat

In [ ]:
mat[:row]  

In [ ]:
mat

In [ ]:
mat[row:] 

In [ ]:
mat[:]

In [ ]:
mat[:,8] 

In [ ]:
mat

In [ ]:
mat[:,-1] 

In [ ]:
mat

In [ ]:
row

In [ ]:
col

In [ ]:
mat[:,col] 

In [ ]:
mat

In [ ]:
mat[1,4]

In [ ]:
mat

In [ ]:
mat[1:4]

In [ ]:
mat

In [ ]:
mat[3:-3]

In [ ]:
mat

In [ ]:
mat[0]

In [ ]:
mat[6]

In [ ]:
mat

In [ ]:
mat[6:]

In [ ]:
mat[:6]

In [ ]:
mat

In [ ]:
mat[5:7]

In [ ]:
mat

In [ ]:
mat[0:10]

In [ ]:
mat

In [ ]:
mat[0:10:3]

In [ ]:
mat[0:10]

In [ ]:
mat[0:10:3]

In [ ]:
mat

In [ ]:
mat[4:]

In [ ]:
mat

In [ ]:
mat[:4]

In [ ]:
mat

In [ ]:
mat[::-1]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-3]

In [ ]:
mat

In [ ]:
mat[::-5]

In [ ]:
mat

In [ ]:
mat[2:6]

In [185]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [186]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [ ]:
mat

In [ ]:
mat[0,1]

In [ ]:
mat[1,6]

In [ ]:
mat

In [ ]:
mat[1:6]

In [ ]:
mat[1:]

In [ ]:
mat

In [ ]:
mat[:6]

In [ ]:
mat[0:1]

In [ ]:
mat

In [ ]:
mat[3:5]

In [ ]:
mat[3,5]

In [187]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [188]:
mat[1:2,2:4] 

array([[12, 13]])

In [189]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat[2:3,2:3] 

In [190]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [191]:
mat[2:4,3:5]

array([[23, 24],
       [33, 34]])

In [ ]:
mat[3:5,2:4]

In [ ]:
mat

In [ ]:
mat[2:3,4:5]

## Masking

In [192]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [193]:
id(mat)

2325687127184

In [194]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [ ]:
mat > 50

In [ ]:
mat[mat==50] 

In [ ]:
mat

In [ ]:
mat == 50

In [ ]:
mat

In [ ]:
a1 = mat[mat<50] 
a1

In [ ]:
mat

In [ ]:
a2 = mat[mat>50] 
a2

In [ ]:
a3 = mat[mat<=50] 
a3

In [ ]:
a4 = mat[mat==50]
a4

# python program to generat otp 

In [208]:
import random

def generate_otp(length=4):
    """Generate a numeric OTP of a specified length."""
    digits = '012345'
    otp = ''.join(random.choice(digits) for _ in range(length))
    return otp

# Example usage
otp_length = 4  # You can change this to any length you prefer
otp = generate_otp(otp_length)
print(f"Your OTP is: {otp}")

Your OTP is: 2034
